version: '3'
services:
  mazzoleniodontologia:
    image: mazzoleniodontologia
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./components:/app/components
      - ./hooks:/app/hooks
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles